Repository sparta-i4/i4-be, pull requests merged in 2025-02, with the labels that each got.

#2 Feature/product system
  src/main/java/com/business/i4_be/domain/product/constants/ProductStatus.java
  src/main/java/com/business/i4_be/domain/product/controller/ProductController.java
  src/main/java/com/business/i4_be/domain/product/controller/ProductOwnerController.java
  src/main/java/com/business/i4_be/domain/product/dto/AddProductReqDto.java
  src/main/java/com/business/i4_be/domain/product/dto/AddProductResDto.java
  src/main/java/com/business/i4_be/domain/product/dto/ProductResDto.java
  src/main/java/com/business/i4_be/domain/product/dto/ProductsResDto.java
  src/main/java/com/business/i4_be/domain/product/dto/UpdateProductReqDto.java
  src/main/java/com/business/i4_be/domain/product/dto/UpdateProductResDto.java
  src/main/java/com/business/i4_be/domain/product/entity/Product.java
  src/main/java/com/business/i4_be/domain/product/repository/ProductRepository.java
  src/main/java/com/business/i4_be/domain/product/service/ProductService.java
  src/main/java/com/business/i4_be/global/config/JpaAuditingConfig.java
  src/main/java/com/business/i4_be/global/exception/ErrorCode.java
  src/main/java/com/business/i4_be/global/exception/ErrorResponse.java
  src/main/java/com/business/i4_be/global/exception/GlobalExceptionHandler.java
  src/test/java/com/business/i4_be/domain/product/repository/ProductRepositoryTest.java
Labels: 🎨structure

#3 feat : Cart 시스템 설계
  src/main/java/com/business/i4_be/domain/cart/controller/CartController.java
  src/main/java/com/business/i4_be/domain/cart/dto/AddCartReqDto.java
  src/main/java/com/business/i4_be/domain/cart/dto/CartResDto.java
  src/main/java/com/business/i4_be/domain/cart/dto/UpdateCartReqDto.java
  src/main/java/com/business/i4_be/domain/cart/entity/Cart.java
  src/main/java/com/business/i4_be/domain/cart/entity/ProductCart.java
  src/main/java/com/business/i4_be/domain/cart/repository/CartRepository.java
  src/main/java/com/business/i4_be/domain/cart/repository/ProductCartRepository.java
  src/main/java/com/business/i4_be/domain/cart/service/CartService.java
Labels: 🎨structure

#4 Feature/payment
  src/main/java/com/business/i4_be/domain/payment/controller/PaymentController.java
  src/main/java/com/business/i4_be/domain/payment/dto/request/PaymentReqDto.java
  src/main/java/com/business/i4_be/domain/payment/dto/response/PaymentResDto.java
  src/main/java/com/business/i4_be/domain/payment/repository/PaymentRepository.java
  src/main/java/com/business/i4_be/domain/payment/service/PaymentService.java
Labels: 🎨structure

#5 feat : 상품 등록 서비스 추가
  src/main/java/com/business/i4_be/domain/product/controller/ProductController.java
  src/main/java/com/business/i4_be/domain/product/dto/AddProductReqDto.java
  src/main/java/com/business/i4_be/domain/product/dto/AddProductResDto.java
  src/main/java/com/business/i4_be/domain/product/entity/Product.java
  src/main/java/com/business/i4_be/domain/product/repository/ProductRepository.java
  src/main/java/com/business/i4_be/domain/product/service/ProductService.java
  src/main/java/com/business/i4_be/global/exception/ErrorCode.java
  src/test/java/com/business/i4_be/domain/product/service/ProductServiceTest.java
  src/test/java/com/business/i4_be/domain/product/service/ProductServiceUnitTest.java
Labels: ✨feature, ✅test

#6 feat : 상품 조회 기능 추가
  src/main/java/com/business/i4_be/domain/product/controller/ProductOwnerController.java
  src/main/java/com/business/i4_be/domain/product/dto/ProductResDto.java
  src/main/java/com/business/i4_be/domain/product/dto/ProductsResDto.java
  src/main/java/com/business/i4_be/domain/product/entity/Product.java
  src/main/java/com/business/i4_be/domain/product/repository/ProductRepository.java
  src/main/java/com/business/i4_be/domain/product/service/ProductService.java
  src/main/java/com/business/i4_be/global/exception/ErrorCode.java
Labels: ✨feature

#8 Feature/order 주문 도메인 CRUD구현
  src/main/java/com/business/i4_be/domain/order/controller/OrderController.java
  src/main/java/com/business/i4_be/domain/order/dto/request/OrderReqDto.java
  src/main/java/com/business/i4_be/domain/order/dto/response/OrderResDto.java
  src/main/java/com/business/i4_be/domain/order/entity/Order.java
  src/main/java/com/business/i4_be/domain/order/entity/OrderProduct.java
  src/main/java/com/business/i4_be/domain/order/repository/OrderRepository.java
  src/main/java/com/business/i4_be/domain/order/service/OrderService.java
  src/test/java/com/business/i4_be/domain/order/service/OrderServiceTest.java
Labels: ✨feature, ✅test

#7 Feature/store crud
  src/main/java/com/business/i4_be/domain/store/constant/StoreCategory.java
  src/main/java/com/business/i4_be/domain/store/controller/StoreController.java
  src/main/java/com/business/i4_be/domain/store/dto/StoreListResDto.java
  src/main/java/com/business/i4_be/domain/store/dto/StoreReqDto.java
  src/main/java/com/business/i4_be/domain/store/dto/StoreResDto.java
  src/main/java/com/business/i4_be/domain/store/dto/StoreUpdateReqDto.java
  src/main/java/com/business/i4_be/domain/store/entity/Store.java
  src/main/java/com/business/i4_be/domain/store/repository/StoreRepository.java
  src/main/java/com/business/i4_be/domain/store/service/StoreService.java
  src/main/java/com/business/i4_be/global/entity/BaseEntity.java
  src/main/java/com/business/i4_be/global/exception/ErrorCode.java
Labels: ✨feature

#9 Feature/user User 도메인 구현
  build.gradle
  src/main/java/com/business/i4_be/domain/user/controller/AuthController.java
  src/main/java/com/business/i4_be/domain/user/controller/UserController.java
  src/main/java/com/business/i4_be/domain/user/dto/request/SigninRequest.java
  src/main/java/com/business/i4_be/domain/user/dto/request/SignupRequest.java
  src/main/java/com/business/i4_be/domain/user/dto/request/UpdateUserRequest.java
  src/main/java/com/business/i4_be/domain/user/dto/response/SigninResponse.java
  src/main/java/com/business/i4_be/domain/user/dto/response/SignupResponse.java
  src/main/java/com/business/i4_be/domain/user/dto/response/UserResponse.java
  src/main/java/com/business/i4_be/domain/user/entity/User.java
  src/main/java/com/business/i4_be/domain/user/repository/UserRepository.java
  src/main/java/com/business/i4_be/domain/user/security/UserDetailsImpl.java
  src/main/java/com/business/i4_be/domain/user/security/UserDetailsServiceImpl.java
  src/main/java/com/business/i4_be/domain/user/service/AuthService.java
  src/main/java/com/business/i4_be/domain/user/service/CustomUserDetailsService.java
  src/main/java/com/business/i4_be/domain/user/service/UserService.java
  src/main/java/com/business/i4_be/global/config/CorsConfig.java
  src/main/java/com/business/i4_be/global/config/SecurityConfig.java
  src/main/java/com/business/i4_be/global/exception/ExceptionHandlerFilter.java
  src/main/java/com/business/i4_be/global/jwt/JwtFilter.java
  src/main/java/com/business/i4_be/global/jwt/JwtUtil.java
  src/main/java/com/business/i4_be/global/jwt/TokenDto.java
  src/main/java/com/business/i4_be/global/jwt/TokenProvider.java
  src/main/java/com/business/i4_be/global/jwt/TokenStatus.java
Labels: ✨feature

#12 Feature/review crud 기능 구현
  src/main/java/com/business/i4_be/domain/order/dto/request/OrderReqDto.java
  src/main/java/com/business/i4_be/domain/order/dto/response/OrderResDto.java
  src/main/java/com/business/i4_be/domain/order/entity/Order.java
  src/main/java/com/business/i4_be/domain/order/service/OrderService.java
  src/main/java/com/business/i4_be/domain/review/controller/ReviewController.java
  src/main/java/com/business/i4_be/domain/review/dto/ReviewReqDto.java
  src/main/java/com/business/i4_be/domain/review/dto/ReviewResDto.java
  src/main/java/com/business/i4_be/domain/review/entity/Review.java
  src/main/java/com/business/i4_be/domain/review/repository/ReviewRepository.java
  src/main/java/com/business/i4_be/domain/review/service/ReviewService.java
  src/main/java/com/business/i4_be/domain/store/repository/StoreRepository.java
Labels: ✨feature, ♻️refactor

#14 refactor: Error처리 리팩토링
  src/main/java/com/business/i4_be/domain/order/service/OrderService.java
  src/main/java/com/business/i4_be/global/exception/ErrorCode.java
Labels: ♻️refactor

#13 feat : Cart CURD 기능 구현
  build.gradle
  src/main/java/com/business/i4_be/domain/cart/controller/CartController.java
  src/main/java/com/business/i4_be/domain/cart/dto/AddCartReqDto.java
  src/main/java/com/business/i4_be/domain/cart/dto/CartResDto.java
  src/main/java/com/business/i4_be/domain/cart/dto/UpdateCartReqDto.java
  src/main/java/com/business/i4_be/domain/cart/entity/Cart.java
  src/main/java/com/business/i4_be/domain/cart/entity/ProductCart.java
  src/main/java/com/business/i4_be/domain/cart/repository/CartRepository.java
  src/main/java/com/business/i4_be/domain/cart/service/CartService.java
  src/main/java/com/business/i4_be/global/config/SecurityConfig.java
  src/main/java/com/business/i4_be/global/exception/ErrorCode.java
Labels: ✨feature

#16 refactor: payment Error처리 리팩토링
  src/main/java/com/business/i4_be/domain/payment/service/PaymentService.java
  src/main/java/com/business/i4_be/global/exception/ErrorCode.java
Labels: ♻️refactor

#17 feat : Product Update, delete 구현 및 Product service refactor
  src/main/java/com/business/i4_be/domain/product/controller/ProductController.java
  src/main/java/com/business/i4_be/domain/product/controller/ProductOwnerController.java
  src/main/java/com/business/i4_be/domain/product/dto/AddProductReqDto.java
  src/main/java/com/business/i4_be/domain/product/dto/AddProductResDto.java
  src/main/java/com/business/i4_be/domain/product/dto/ProductResDto.java
  src/main/java/com/business/i4_be/domain/product/dto/UpdateProductReqDto.java
  src/main/java/com/business/i4_be/domain/product/dto/UpdateProductResDto.java
  src/main/java/com/business/i4_be/domain/product/entity/Product.java
  src/main/java/com/business/i4_be/domain/product/repository/ProductRepository.java
  src/main/java/com/business/i4_be/domain/product/service/ProductService.java
  src/main/java/com/business/i4_be/global/config/SecurityConfig.java
Labels: ✨feature, ♻️refactor

#18 Feature/user: Address, 탈퇴, 관리자 계정 생성, 권한 수정
  src/main/java/com/business/i4_be/domain/user/controller/AuthController.java
  src/main/java/com/business/i4_be/domain/user/controller/UserController.java
  src/main/java/com/business/i4_be/domain/user/dto/request/AddressRequest.java
  src/main/java/com/business/i4_be/domain/user/dto/request/SignupRequest.java
  src/main/java/com/business/i4_be/domain/user/dto/request/UpdateUserRequest.java
  src/main/java/com/business/i4_be/domain/user/dto/request/UserSigninRequest.java
  src/main/java/com/business/i4_be/domain/user/dto/request/UserSignupRequest.java
  src/main/java/com/business/i4_be/domain/user/dto/request/UserUpdateWrapper.java
  src/main/java/com/business/i4_be/domain/user/dto/response/AddressResponse.java
  src/main/java/com/business/i4_be/domain/user/dto/response/SigninResponse.java
  src/main/java/com/business/i4_be/domain/user/dto/response/SignupResponse.java
  src/main/java/com/business/i4_be/domain/user/dto/response/UserResponse.java
  src/main/java/com/business/i4_be/domain/user/dto/response/UserResponseWrapper.java
  src/main/java/com/business/i4_be/domain/user/entity/Address.java
  src/main/java/com/business/i4_be/domain/user/entity/User.java
  src/main/java/com/business/i4_be/domain/user/security/UserDetailsImpl.java
  src/main/java/com/business/i4_be/domain/user/service/AddressService.java
  src/main/java/com/business/i4_be/domain/user/service/AuthService.java
  src/main/java/com/business/i4_be/domain/user/service/UserService.java
  src/main/java/com/business/i4_be/global/config/DataInitializer.java
  src/main/java/com/business/i4_be/global/config/SecurityConfig.java
  src/main/java/com/business/i4_be/global/exception/CustomAccessDeniedHandler.java
  src/main/java/com/business/i4_be/global/exception/ErrorCode.java
  src/main/java/com/business/i4_be/global/exception/ExceptionHandlerFilter.java
  src/main/java/com/business/i4_be/global/jwt/JwtFilter.java
Labels: ✨feature, ♻️refactor

#19 test: product - 등록, 수정, 삭제 테스트 코드 추가
  .gitignore
  src/main/java/com/business/i4_be/domain/product/dto/UpdateProductReqDto.java
  src/main/java/com/business/i4_be/domain/product/service/ProductService.java
  src/test/java/com/business/i4_be/common/DeleteSupport.java
  src/test/java/com/business/i4_be/config/TearDownExecutor.java
  src/test/java/com/business/i4_be/domain/product/repository/ProductRepositoryTest.java
  src/test/java/com/business/i4_be/domain/product/service/ProductServiceTest.java
  src/test/java/com/business/i4_be/domain/product/service/ProductServiceUnitTest.java
Labels: ✅test

#20 Refactor/store adduserinfo
  build.gradle
  src/main/java/com/business/i4_be/domain/store/controller/StoreController.java
  src/main/java/com/business/i4_be/domain/store/controller/StoreOwnerController.java
  src/main/java/com/business/i4_be/domain/store/dto/PagedResDto.java
  src/main/java/com/business/i4_be/domain/store/dto/StoreOwnerUpdateReqDto.java
  src/main/java/com/business/i4_be/domain/store/dto/StoreReqDto.java
  src/main/java/com/business/i4_be/domain/store/dto/StoreResDto.java
  src/main/java/com/business/i4_be/domain/store/entity/Store.java
  src/main/java/com/business/i4_be/domain/store/repository/StoreRepository.java
  src/main/java/com/business/i4_be/domain/store/repository/StoreRepositoryCustom.java
  src/main/java/com/business/i4_be/domain/store/repository/StoreRepositoryImpl.java
  src/main/java/com/business/i4_be/domain/store/service/StoreService.java
  src/main/java/com/business/i4_be/domain/user/repository/UserRepository.java
  src/main/java/com/business/i4_be/global/config/QuerydslConfig.java
  src/main/java/com/business/i4_be/global/config/SecurityConfig.java
  src/main/java/com/business/i4_be/global/exception/ErrorCode.java
Labels: ✨feature, ♻️refactor

#22 Feature/user
  src/main/java/com/business/i4_be/domain/address/controller/AddressController.java
  src/main/java/com/business/i4_be/domain/address/dto/request/AddressReqDto.java
  src/main/java/com/business/i4_be/domain/address/dto/response/AddressResDto.java
  src/main/java/com/business/i4_be/domain/address/entity/Address.java
  src/main/java/com/business/i4_be/domain/address/repository/AddressRepository.java
  src/main/java/com/business/i4_be/domain/address/service/AddressService.java
  src/main/java/com/business/i4_be/domain/order/entity/Order.java
  src/main/java/com/business/i4_be/domain/order/service/OrderService.java
  src/main/java/com/business/i4_be/domain/user/controller/UserController.java
  src/main/java/com/business/i4_be/domain/user/dto/request/UpdateUserRequest.java
  src/main/java/com/business/i4_be/domain/user/dto/response/AddressResponse.java
  src/main/java/com/business/i4_be/domain/user/dto/response/UserResponse.java
  src/main/java/com/business/i4_be/domain/user/entity/Address.java
  src/main/java/com/business/i4_be/domain/user/entity/User.java
  src/main/java/com/business/i4_be/domain/user/service/AddressService.java
  src/main/java/com/business/i4_be/domain/user/service/UserService.java
  src/main/java/com/business/i4_be/global/exception/ErrorCode.java
  src/test/java/com/business/i4_be/domain/order/service/OrderServiceTest.java
Labels: ✨feature, ♻️refactor

#21 Refactor/review
  src/main/java/com/business/i4_be/domain/review/controller/ReviewController.java
  src/main/java/com/business/i4_be/domain/review/dto/PagedResDto.java
  src/main/java/com/business/i4_be/domain/review/dto/ReviewResDto.java
  src/main/java/com/business/i4_be/domain/review/repository/ReviewRepository.java
  src/main/java/com/business/i4_be/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/business/i4_be/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/business/i4_be/domain/review/service/ReviewService.java
  src/main/java/com/business/i4_be/global/config/AuditorAwareImpl.java
  src/main/java/com/business/i4_be/global/config/JpaAuditingConfig.java
  src/main/java/com/business/i4_be/global/config/SecurityConfig.java
Labels: ✨feature, ♻️refactor

#23 refactor: Product 도메인 페이징 처리 / Enum BeanValidation 처리
  src/main/java/com/business/i4_be/domain/product/constants/ProductStatus.java
  src/main/java/com/business/i4_be/domain/product/controller/ProductController.java
  src/main/java/com/business/i4_be/domain/product/dto/AddProductReqDto.java
  src/main/java/com/business/i4_be/domain/product/dto/PageProductsResDto.java
  src/main/java/com/business/i4_be/domain/product/dto/UpdateProductReqDto.java
  src/main/java/com/business/i4_be/domain/product/repository/ProductRepository.java
  src/main/java/com/business/i4_be/domain/product/service/ProductService.java
  src/main/java/com/business/i4_be/global/annotation/ValidEnum.java
  src/main/java/com/business/i4_be/global/config/SecurityConfig.java
  src/main/java/com/business/i4_be/global/exception/GlobalExceptionHandler.java
  src/main/java/com/business/i4_be/global/validation/EnumValidator.java
Labels: ♻️refactor

#25 feat: Aop 로깅 처리
  build.gradle
  src/main/java/com/business/i4_be/global/aop/AopLogging.java
  src/main/resources/logback-spring.xml
Labels: ✨feature

#27 refactor : product 리팩토링 및 상태변경 API 추가
  src/main/java/com/business/i4_be/domain/product/controller/ProductOwnerController.java
  src/main/java/com/business/i4_be/domain/product/dto/UpdateStatusProductReqDto.java
  src/main/java/com/business/i4_be/domain/product/dto/UpdateStatusProductResDto.java
  src/main/java/com/business/i4_be/domain/product/repository/ProductRepository.java
  src/main/java/com/business/i4_be/domain/product/service/ProductService.java
  src/main/java/com/business/i4_be/domain/store/dto/StoreListResDto.java
  src/main/java/com/business/i4_be/domain/store/dto/StoreUpdateReqDto.java
  src/main/java/com/business/i4_be/global/config/SecurityConfig.java
  src/main/java/com/business/i4_be/global/jwt/JwtFilter.java
  src/test/java/com/business/i4_be/domain/product/service/ProductServiceTest.java
  src/test/java/com/business/i4_be/domain/product/service/ProductServiceUnitTest.java
Labels: ✨feature, ♻️refactor

#29 fix: 테스트코드 수정
  src/main/java/com/business/i4_be/domain/order/service/OrderService.java
  src/test/java/com/business/i4_be/domain/order/service/OrderServiceTest.java
Labels: bug

#30 fix: orderType 제대로 반환 안되는 문제 해결
  src/main/java/com/business/i4_be/domain/order/dto/response/OrderResDto.java
  src/main/java/com/business/i4_be/domain/order/entity/Order.java
  src/main/java/com/business/i4_be/domain/order/service/OrderService.java
Labels: bug
